#define FILE_CAP_REACHED -1
#define FILE_OPEN -2
#define INVALID_MODE -3
#define FILE_NOT_FOUND -4
#define NO_OPEN_FILES -5
#define INVALID_ID -6
#define FILE_NOT_OPEN -7
#define ERR_NGTV -8
#define ERR_CAP_REACHED -9
#define BAD_DIR -10
#define ROOT_RMV_ERR -11 
